# Listado de instituciones
orgs <- c("feuc", "feusach", "la_fech", "confech", "mesup_Chile", "difusion_ACES", "feuv", "ucscconcepcion", "FECUdeC", "CONESCHILE", "UNE_CHILE", "com_fech", "feutfsm", "FEUSAM", "FEVUNAB", "secundarios", "FEUAI_stgo", "FEUANDES", "FEL_Stgo", "Feutal2013", "FEDEPUDP", "_FEUCEN", "FEUDD_stgo", "FEUBO_OFICIAL", "FeustSantiago", "FEPUCV", "FEUTEM", "FEUDMVina", "FepPedagogico", "FELUCHILE", "FEUFRO", "feubb", "FEUAntofagasta", "Feupla", "DelegConfechUC", "feusmjmc", "FEUCN", "FeuachUACH", "Feuls", "feuvsantiago", "FEUCM2011", "FEDEUNAP", "feucncqbo", "la_Fech", "Bienestar_FECh", "Une_Santiago", "CeapUsach2013", "Feuc", "feuahurtado", "CACoUC", "FOACHcl", "PropeUsach", "Difusion_ACES", "Feudem_Talca", "Feuv", "Feuls13", "FEUAI_vina", "feul_osorno", "feudlaconce", "FeUpla", "FedeumCurico", "FEUDLA_", "fedeumsanfer", "feufro", "FEUVStgo", "FundacionFEDES", "Feul_PtoMontt", "feummagallanes", "Feubbchillan", "Feudla_VL", "FEJ_Chile", "FEUDD_STGO", "SecundariosJS", "SecundariosJJCC", "FeutfsmConceRbb", "Juventudhuastek", "FELsecundarios", "FederacionUA", "FEC_Chillan", "FEPUC")

# Listado de movimientos
movs <- c("ccp_movilizada", "La_PezEra", "manecolombia", "yodebocl", "1800horas", "soyvalparaiso", "ciclopatagonia", "twittsejero", "mfc_oficial", "bicicultura", "heavyciclistas", "vidaoutdoor", "ciclistaseduc", "maqmaravillosa", "vivelabici", "comunistamexico", "indignateco", "prensaestudiant", "confidencialcol", "radicalyfeliz", "colpoderpopular", "link_anarquista", "anonchileno", "fdialoga", "jjcc_chile", "amnistiachile", "jsusach", "caipuc", "twittsejera", "tomalafacultad", "trabajo_chile", "soychilecl", "anefchile", "oposicionpinera", "happyciclistas", "cicilistaseduc", "educacion2020", "superarpobreza", "universitecl", "ciclismourbano", "yomesumo", "yonovotexel", "nolesvoteschile", "aministiachile", "aqui_leo", "Rdemocratica", "coneschile", "marcoporchile", "lafundacionsol", "ChileaLaMoneda", "Estafados_CORFO", "Izquierda_Tuit", "naupuc", "mguc", "izqautonoma", "u_informado", "infestudiantes", "creceruc", "SolidaridadUC", "DeudaEducativa", "valdivianos", "informanteUDA", "privmovilizadas", "MACEUAI", "soydederecha", "brigadachacon", "CREASUAH", "marxismo_cl", "CiudadaniaDenun", "la_confesh", "CeapUsach2013", "MovilizateChile", "mesup_chile", "RDValdivia", "profes_UCENTRAL", "centroGAM", "SomosLasF3", "Chilejusto2012", "Cacerolachilena", "AccionChileVerd", "NOaBachelet", "CACoUC", "oindependiente", "GNoViolenta", "MedicosPorChile", "canal_chile", "acciongay", "Rev_ecoamerica", "ElChilenero", "difamadores", "juventupolitica", "Humanidades_Uch", "Infestudiantes", "DerechaTuitera", "CENDA_chile", "ProAccesoChile", "PAIEPUSACH", "InformanteUDA", "fel_chile", "Feudem_Iqq", "Privmovilizadas", "EstafadosCorfo9", "PPDbiobio", "JuventudGuzman", "Juventudes_PRI", "movimientosurda", "democraciareal", "IgualesChile", "igualeschile", "FundJaimeGuzman", "JuventudRebelde", "Juvenil_Iguales", "FundacionFEDES", "juventudCCS", "PPD_Chile", "FundacionPuente", "FundacionPortas", "PPDStgoCentro", "PDC_Chile", "fundacionchile", "JuventudClaude", "FeudlaSomostods", "JuventudPSUV", "EstafadosUDM", "EndeudadosCorfo", "fundacionLJ", "JuventudVolante", "FundTemplanza", "FedPalestina", "JvenesXBachelet", "JuvProvidencia", "EstafadosporBan", "Juventud_PPD", "SecundariosJS", "SecundariosJJCC", "Juventudhuastek", "FundacionAVINA", "FELsecundarios", "FundLasRosas", "JuventudenMarc", "JuventudLibrehn", "fundacionRAYUNd", "SecundariosJota", "JuventuDurango", "Fundacion_Tacal", "Juventud_UDI_30", "juventududivina", "Cores_PPD", "juventudecut", "FundacionDecide", "JUVINDxMICHELLE", "FundacionFilba", "AC_Chile", "INJUVCHILE", "pdcprovidencia", "izqautonomauc")

# Listado de líderes
leaders <- c("camila_vallejo", "valenzuelalevi", "srcrispin", "GiorgioJackson", "Sr_Ballesteros", "panchofigueroa", "velagrau", "AFielbaum", "gabrielboric", "NoamTitelman", "sebavielmas", "ANKALAO", "elperrotracio", "feliperasa", "RebecaGaeteS", "SDonoso_", "_marioalbertod", "danirslz", "PabloReyes_F", "sebafarfans", "marjoriecuello", "MoisesParedesR", "pepoglatz", "recarex", "PMillalen", "Pato_Contreras_", "jorbritoh", "SebaGodoyElguet", "goyarzun", "unavico", "j_miranda_s", "sebagamboa_", "vlatorre", "felipevargasr", "_isabelsalgado", "florespineda", "raecheco", "IriarteCORE", "acouble", "camiloriffo", "palta_mayo", "Godoy_JC", "pjgonzalez_", "leoiec", "NatalyEspin0za", "aalegred", "elRodrigoDuran", "Felipesalga", "guillermo_peter", "Javier_Fano", "intialavia", "IsmaelSoruco", "geo_sur", "FranciscoSainz", "FdaSandoval", "DanielaPobleteP", "Patricio_Indo", "krivera_uls", "ConstanzaLeyton", "BorisNegrete", "InzulzaAlberto", "Fco_Acunac", "OrleansRomero", "alexis_gonzlz", "pablo_fepucv", "d_cid", "Chriistopher_xD", "andresdouglasr", "Pipovaldebenito", "vargassasmay", "Carolina_Jarap", "DanaeDiazJeria", "Valeilic", "Javijadue", "EliasLonconado", "carlos_ruminott", "alvarobeckdorf", "Cris_Sarabia", "bernardo_barria", "jmiguelprieto", "YoxcyCampos", "Paonessa", "AngelitaJaviera", "carocatomas", "henry_varas", "Valessoncilla", "CrisLagos", "Mapa_Ruiz_", "germainquintana", "Franciscolabrav", "Coni_nogues", "pipe_higueras", "josefinaprivas", "Karolcariola", "_EloisaGonzalez")

# Listado de medios
medios <- c("el_dinamo", "diariolider", "sentidoscomunes", "elquintopoder", "elespectador", "austral_losrios", "austral_osorno", "lidersanantonio", "elcomerciocom",  "opanoticias", "phumano", "eltiempo", "thecliniccl", "nacioncl", "larepublica_pe", "latercera", "cooperativa", "votainteligente", "cnnchile", "canal_chile", "rvfradiopopular", "tvparachile", "radiosantamaria", "elmostrador", "tolerancia0", "elpost_cl", "mercuriovalpo", "mercurioafta", "diarioafta", "laotravoz", "soyarica")

# Listado de personalidades (periodistas, políticos, columnistas, etc)
famosos <- c("illapu", "intihistorico", "inti_historico", "tvn_mauricio", "copano", "soledadalvear", "lostres", "marcelodiazd", "fernandopaulsen", "inti_illimani", "mwaissbluth", "biobio", "mercuriovalpo", "alfonsoconcha", "sboric", "flaitechileno", "pcayuqueo", "renenaranjo", "toledo_campos", "mariseka", "hectorcaldera", "elterribledios", "danieljadue", "sobras", "aalaluf", "jaimegajardo", "ingridcruztoro", "sesnaola", "ignaciowalker", "pablosimonetti", "adribarrientos", "ivanguerrerom", "LuisLarrain", "ahsoffia")
